version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install pytest ruff
      - run: pytest

workflows:
  pipeline:
    jobs:
      - build
